// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ConnectLink: typeof import('./src/components/ConnectLink.vue')['default']
    ContainerAuth: typeof import("./src/pages/auth/ContainerAuth.vue")["default"]
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
